[package]
name = "zkmemory"
version = "0.1.0"
edition = "2021"
description = "A ECVRF that's friendly with EVM, based on cur secp256k1 and keccak256"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
